Repository Track-Save/backend, pull requests merged in 2025-07, with the labels that each got.

#125 fix: Hash na criação dos produtos com atualização de preço
  track_save/api/controllers/product_controller.py
  track_save/api/entities/product.py
  track_save/api/migrations/0015_alter_product_hash.py
Labels: fix

#126 TSV 51 - feat: Correções gerais de formatação e Salvando produtos da Kabum no Banco local
  .gitignore
  README.md
  pyproject.toml
  track_save/__init__.py
  track_save/api/controllers/product_controller.py
  track_save/api/entities/__init__.py
  track_save/api/entities/price.py
  track_save/api/entities/product.py
  track_save/api/entities/user.py
  track_save/api/enums/__init__.py
  track_save/api/enums/category_specs.py
  track_save/api/migrations/0016_alter_storage_read_speed_alter_storage_write_speed_and_more.py
  track_save/api/migrations/0017_alter_computer_inches_alter_computer_ram_and_more.py
  track_save/api/migrations/0018_alter_computer_color_support_alter_computer_gpu_and_more.py
  track_save/api/migrations/0019_alter_product_description.py
  track_save/api/views/product_views.py
  track_save/webscraping/scrapers/kabum.py
  track_save/webscraping/scrapers/scraper.py
  track_save/webscraping/scrapers/specific_data/__init__.py
  track_save/webscraping/scrapers/specific_data/gpu.py
  track_save/webscraping/urls.py
  track_save/webscraping/views.py
  track_save/webscraping/webscraping_factory.py
Labels: feat, fix

#133 feat: implementação de função e chatbot integrado
  track_save/api/controllers/product_controller.py
  track_save/api/urls.py
  track_save/api/views/product_views.py
  track_save/chatbot/agents/agent_upgrade.py
  track_save/chatbot/agents/agent_use.py
  track_save/chatbot/views.py
Labels: feat

#144 TSV-47 - fix: Paginação no Scrapper da Kabum e revisão dos campos de info específicas
  .github/workflows/ci.yml
  track_save/api/enums/category_specs.py
  track_save/webscraping/enums.py
  track_save/webscraping/scrapers/kabum.py
  track_save/webscraping/scrapers/scraper.py
  track_save/webscraping/scrapers/specific_data/cpu.py
  track_save/webscraping/scrapers/specific_data/keyboard.py
  track_save/webscraping/scrapers/specific_data/mouse.py
  track_save/webscraping/scrapers/specific_data/ram.py
Labels: bug, fix

#114 Envio de emails usando template
  track_save/api/controllers/user_controller.py
  track_save/api/templates/emails/confirm_email.html
  track_save/api/templates/emails/reset_password.html
Labels: feat

#154 Feature/tsv 34
  track_save/api/controllers/favorite_controller.py
  track_save/api/controllers/price_controller.py
  track_save/api/controllers/product_controller.py
  track_save/api/urls.py
  track_save/api/views/alert_views.py
  track_save/api/views/favorite_views.py
Labels: feat

#156 TSV-65 fix: Ajustes agente
  track_save/api/controllers/product_controller.py
  track_save/chatbot/agents/agent_upgrade.py
  track_save/chatbot/agents/agent_use.py
  track_save/webscraping/scrapers/kabum.py
Labels: fix

#165 hotfix: Ajustes migrations
  track_save/api/migrations/0023_add_default_subscription.py
  track_save/api/migrations/0026_populate_subscription_details.py
Labels: bug
