Repository Track-Save/backend, pull requests merged in 2025-06, with the labels that each got.

#47 feat: adicionando o cors
  config/settings/base.py
  requirements/base.txt
  track_save/api/views/user_views.py
Labels: chore

#62 TSV-09 feat: App do WebScraping com Implementação Inicial do Webscraping da Kabum
  .devcontainer/devcontainer.json
  compose/local/django/Dockerfile
  config/urls.py
  requirements/base.txt
  track_save/webscraping/__init__.py
  track_save/webscraping/admin.py
  track_save/webscraping/apps.py
  track_save/webscraping/enums.py
  track_save/webscraping/migrations/__init__.py
  track_save/webscraping/models.py
  track_save/webscraping/scrapers/__init__.py
  track_save/webscraping/scrapers/kabum.py
  track_save/webscraping/scrapers/scraper.py
  track_save/webscraping/tests.py
  track_save/webscraping/urls.py
  track_save/webscraping/views.py
  track_save/webscraping/webscraping_factory.py
Labels: feat, docker

#81 Tsv 31
  track_save/api/controllers/price_controller.py
  track_save/api/controllers/product_controller.py
  track_save/api/entities/product.py
  track_save/api/migrations/0007_insert_stores.py
  track_save/api/migrations/0008_alter_product_category.py
  track_save/api/urls.py
  track_save/api/views/price_views.py
  track_save/api/views/product_views.py
Labels: feat

#83 Feature/tsv 13
  config/settings/base.py
  track_save/api/serielizers/__init__.py
  track_save/api/serielizers/login_serielizers.py
  track_save/api/serielizers/user_data_serializers.py
  track_save/api/urls.py
  track_save/api/views/user_views.py
Labels: feat
